services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - --api-version
      - "1.55"
      - --cleanup
      - --interval
      - "86400"
