---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmark


- Management:
    - ChatGPT:
        - href: https://chat.openai.com

    - Google Fiber:
        - href: https://fiber.google.com

    - TP-Link:
        - href: https://www.tp-link.com/us/support/

- Documentation:
    - Docker:
        - href: https://docs.docker.com

    - OPNsense:
        - href: https://docs.opnsense.org

    - TrueNAS:
        - href: https://www.truenas.com/docs/
