- Infrastructure:
    - OPNsense:
        href: https://opnsense.osier.local
        icon: opnsense.png
    - Pi-hole:
        href: https://pihole.osier.local
        icon: pi-hole.png
        widget:
          type: pihole
          url: https://pihole.osier.local
          key: ${PIHOLE_API_KEY}
    - TrueNAS:
        href: https://truenas.osier.local
        icon: truenas.png
    - Omada:
        href: https://omada.osier.local
        icon: tp-link.png
- Containers:
    - Homepage:
        href: https://homepage.osier.local
    - Portainer:
        href: https://portainer.osier.local
        widget:
          type: portainer
          url: https://portainer.osier.local
          env: 1
          key: ${PORTAINER_API_KEY}
    - Dozzle:
        href: https://dozzle.osier.local
    - Nginx Proxy Manager:
        href: https://proxy.osier.local
- Monitoring:
    - Grafana:
        href: https://grafana.osier.local
        widget:
          type: grafana
          url: https://grafana.osier.local
          username: ${GRAFANA_USERNAME}
          password: ${GRAFANA_PASSWORD}
    - Prometheus:
        href: https://prometheus.osier.local
    - Uptime Kuma:
        href: https://uptime.osier.local
        widget:
          type: uptimekuma
          url: https://uptime.osier.local
          slug: ${UPTIME_KUMA_SLUG}
    - NetAlertX:
        href: https://netalertx.osier.local
- Security:
    - Nessus:
        href: https://nessus.osier.local
- Applications:
    - Nextcloud:
        href: https://nextcloud.osier.net
    - Immich:
        href: https://immich.osier.net
