---
title: Osier Homelab
theme: dark
color: slate
headerStyle: boxedWidgets
background:
  image: /images/background.webp
  blur: md
  brightness: 35
layout:
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Security:
    style: row
    columns: 3
  Containers:
    style: row
    columns: 4
  Applications:
    style: row
    columns: 3
